[package]
name = "natural-gravity-engine"
version = "0.1.0"
authors = ["Andrew Wang <acwangpython@gmail.com>"]
edition = "2018"
license = "LGPL-3.0"

[dependencies]
amethyst = "0.15.0"
log = "0.4.8"

[features]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
